#pragma once

namespace Engine
{
	enum LEVEL { LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_GAMEPLAY1, LEVEL_GAMEPLAY2, LEVEL_END };

	enum OBJECT_ID { ID_PLAYER, ID_MONSTER, ID_ENVIRONMENT, ID_INSTALLATLON, ID_WEAPON, ID_PEEKING, ID_CELL, ID_CUBE, ID_MIDDLEBOSS, ID_UI, ID_END };

	enum COLLIDERTYPE { COLLTYPE_AABB, COLLTYPE_OBB, COLLTYPE_SPHERE, COLLTYPE_SPHERE_TARGET, COLLTYPE_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };
}